# Deliverable 2. Create a Customer Travel Destinations Map.
----
1. Create a folder called `Vacation_Search` to save all the files related with this deliverable.

2. Download the `Vacation_Search_starter_code.ipynb` Jupyter notebook,save it into your `Vacation_Search folder`, and rename it as `Vacation_Search.ipynb`.

3. In the `Vacation_Search.ipynb` file, ensure that the dependencies and the Google API key is imported correctly.

4. From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame named `city_data_df`.

5. Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

6. Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected. Name the DataFrame as `preferred_cities_df`.

7. Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

8. Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

9. Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

10. Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

11. Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

12. Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

13. Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

14. Review the formatting template provided that you'll use to add an information box to each marker in the map. In the pop-up for each city you'll add:

    1. The city name.

    2. The country code.

    3. The weather description and maximum temperature for the city.

15. Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

16. Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

17. Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

18. Take a screenshot of your map and save it to the `Vacation_Search` folder as `WeatherPy_vacation_map.png`.
---

## Ensure that the dependencies and the Google API key is imported correctly.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import Google API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

## From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame.

In [4]:
# Set the file path to import the WeatherPy_database.csv file
file_path = "../Weather_Database/WeatherPy_database.csv"

# Load the CSV file into a Pandas DataFrame
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")

# Display sample data
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Coahuayana,MX,18.7333,-103.6833,75.27,98,100,2.46,overcast clouds
1,1,Mataura,NZ,-46.1927,168.8643,47.48,45,91,10.07,overcast clouds
2,2,Ushuaia,AR,-54.8000,-68.3000,40.66,81,0,3.44,clear sky
3,3,Ahipara,NZ,-35.1667,173.1667,61.03,85,65,13.18,broken clouds
4,4,Manjacaze,MZ,-24.7117,33.8828,64.24,97,6,5.12,clear sky

## Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

In [5]:
# Prompt the user to enter the minimum temperature criteria
min_temp = float(input("What is your desired minimum temperature for your trip? "))

# Prompt the user to enter the maximum temperature criteria
max_temp = float(input("What is your desired maximum temperature for your trip? "))

What is your desired minimum temperature for your trip? 75
What is your desired maximum temperature for your trip? 85

## Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected.

In [6]:
# Filter the city_data_df DataFrame to find the cities that fit the criteria using the loc Pandas function
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] >= min_temp) &
                                      (city_data_df["Max Temp"] <= max_temp)]
                                    
# Display sample data
preferred_cities_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Coahuayana,MX,18.7333,-103.6833,75.27,98,100,2.46,overcast clouds
6,6,Atuona,PF,-9.8000,-139.0333,77.05,74,35,18.86,light rain
7,7,Bitkine,TD,11.9801,18.2138,76.86,81,78,7.52,broken clouds
13,13,Vaini,TO,-21.2000,-175.2000,78.96,78,75,11.50,broken clouds
17,17,Altamira,BR,-3.2033,-52.2064,78.75,64,71,0.49,broken clouds
...,...,...,...,...,...,...,...,...,...,...
686,686,Touros,BR,-5.1989,-35.4608,75.99,75,9,13.22,clear sky
687,687,Pahrump,US,36.2083,-115.9839,84.25,25,0,5.61,clear sky
696,696,Nawa,IN,27.0167,75.0000,76.44,62,0,12.17,clear sky
700,700,Miri,MY,4.4148,114.0089,82.54,78,40,5.75,light rain
702,702,Alofi,NU,-19.0595,-169.9187,80.49,54,12,14.97,few clouds

## Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

In [7]:
# Drop any empty rows in the preferred_cities_df DataFrame and create a new DataFrame.
clean_travel_cities = preferred_cities_df.dropna()

# Display sample data
clean_travel_cities

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Coahuayana,MX,18.7333,-103.6833,75.27,98,100,2.46,overcast clouds
6,6,Atuona,PF,-9.8000,-139.0333,77.05,74,35,18.86,light rain
7,7,Bitkine,TD,11.9801,18.2138,76.86,81,78,7.52,broken clouds
13,13,Vaini,TO,-21.2000,-175.2000,78.96,78,75,11.50,broken clouds
17,17,Altamira,BR,-3.2033,-52.2064,78.75,64,71,0.49,broken clouds
...,...,...,...,...,...,...,...,...,...,...
686,686,Touros,BR,-5.1989,-35.4608,75.99,75,9,13.22,clear sky
687,687,Pahrump,US,36.2083,-115.9839,84.25,25,0,5.61,clear sky
696,696,Nawa,IN,27.0167,75.0000,76.44,62,0,12.17,clear sky
700,700,Miri,MY,4.4148,114.0089,82.54,78,40,5.75,light rain
702,702,Alofi,NU,-19.0595,-169.9187,80.49,54,12,14.97,few clouds

## Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

In [8]:
# Create DataFrame called hotel_df by copying some columns from the clean_travel_cities DataFrame.
hotel_df = clean_travel_cities[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# Display sample data
hotel_df.head(10)

          City Country  Max Temp Current Description      Lat       Lng
0   Coahuayana      MX     75.27     overcast clouds  18.7333 -103.6833
6       Atuona      PF     77.05          light rain  -9.8000 -139.0333
7      Bitkine      TD     76.86       broken clouds  11.9801   18.2138
13       Vaini      TO     78.96       broken clouds -21.2000 -175.2000
17    Altamira      BR     78.75       broken clouds  -3.2033  -52.2064
18       Kapaa      US     80.92       broken clouds  22.0752 -159.3190
21  San Matias      BO     80.20     overcast clouds -16.3667  -58.4000
22      Shingu      JP     76.44     overcast clouds  33.7333  135.9833
27        Hilo      US     83.93           clear sky  19.7297 -155.0900
28       Kutum      SD     76.91       broken clouds  14.2000   24.6667

## Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

In [9]:
# Add a new empty column, "Hotel Name", to the hotel_df DataFrame
hotel_df["Hotel Name"] = ""

# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Coahuayana,MX,75.27,overcast clouds,18.7333,-103.6833,
6,Atuona,PF,77.05,light rain,-9.8000,-139.0333,
7,Bitkine,TD,76.86,broken clouds,11.9801,18.2138,
13,Vaini,TO,78.96,broken clouds,-21.2000,-175.2000,
17,Altamira,BR,78.75,broken clouds,-3.2033,-52.2064,
18,Kapaa,US,80.92,broken clouds,22.0752,-159.3190,
21,San Matias,BO,80.20,overcast clouds,-16.3667,-58.4000,
22,Shingu,JP,76.44,overcast clouds,33.7333,135.9833,
27,Hilo,US,83.93,clear sky,19.7297,-155.0900,
28,Kutum,SD,76.91,broken clouds,14.2000,24.6667,

## Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

In [10]:
# Review the parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

## Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

In [11]:
# Iterate through the hotel DataFrame 
for index, row in hotel_df.iterrows():
    # Fetch latitude and longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude as parameters to the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Set up the base URL for the Google Directions API to get JSON data
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make an API request and retrieve the JSON data from the hotel search
    hotels = requests.get(base_url, params=params).json()
    
    # Get the first hotel from the results and store the name, if a hotel isn't found skip the city
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [12]:
# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Coahuayana,MX,75.27,overcast clouds,18.7333,-103.6833,El rranchito michuacan de ocampos
6,Atuona,PF,77.05,light rain,-9.8000,-139.0333,Villa Enata
7,Bitkine,TD,76.86,broken clouds,11.9801,18.2138,
13,Vaini,TO,78.96,broken clouds,-21.2000,-175.2000,Keleti Beach Resort
17,Altamira,BR,78.75,broken clouds,-3.2033,-52.2064,Requinte Hotel
18,Kapaa,US,80.92,broken clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
21,San Matias,BO,80.20,overcast clouds,-16.3667,-58.4000,"HOTEL ""SAN JOSE"""
22,Shingu,JP,76.44,overcast clouds,33.7333,135.9833,Shingu UI Hotel
27,Hilo,US,83.93,clear sky,19.7297,-155.0900,Hilo Hawaiian Hotel
28,Kutum,SD,76.91,broken clouds,14.2000,24.6667,Dibbo areaمنطقة دبو

## Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

In [13]:
# Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()

# Display sample data
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Coahuayana,MX,75.27,overcast clouds,18.7333,-103.6833,El rranchito michuacan de ocampos
6,Atuona,PF,77.05,light rain,-9.8000,-139.0333,Villa Enata
7,Bitkine,TD,76.86,broken clouds,11.9801,18.2138,
13,Vaini,TO,78.96,broken clouds,-21.2000,-175.2000,Keleti Beach Resort
17,Altamira,BR,78.75,broken clouds,-3.2033,-52.2064,Requinte Hotel
...,...,...,...,...,...,...,...
686,Touros,BR,75.99,clear sky,-5.1989,-35.4608,INN NEW HORIZON
687,Pahrump,US,84.25,clear sky,36.2083,-115.9839,Best Western Pahrump Oasis
696,Nawa,IN,76.44,clear sky,27.0167,75.0000,"Sambharia Bhawan,Kuchaman Road,Nawa City"
700,Miri,MY,82.54,light rain,4.4148,114.0089,"Mega Hotel, Miri"
702,Alofi,NU,80.49,few clouds,-19.0595,-169.9187,Taloa Heights

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [14]:
# In case of an empty DataFrame, load the sample data provided
# clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
# clean_hotel_df.head(10)

## Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

In [15]:
# Set the file name.
output_data_file = "WeatherPy_vacation.csv"

# Create a CSV file by using the clean_hotel_df DataFrame
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

### Review the formatting template provided that you'll use to add an information box to each marker in the map.

In the pop-up for each city you'll add: 

1. The city name

2. The country code

3. The weather description and maximum temperature for the city

In [16]:
# Review the formatting template provided
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

## Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

In [17]:
# Get the data from each row in the clean_hotel_df DataFrame, add it to the formatting template, and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# Display sample data
hotel_info

['\n<dl>\n<dt>Hotel Name</dt><dd>El rranchito michuacan de ocampos</dd>\n<dt>City</dt><dd>Coahuayana</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 75.27 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Villa Enata</dd>\n<dt>City</dt><dd>Atuona</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Current Weather</dt><dd>light rain and 77.05 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Bitkine</dd>\n<dt>Country</dt><dd>TD</dd>\n<dt>Current Weather</dt><dd>broken clouds and 76.86 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Keleti Beach Resort</dd>\n<dt>City</dt><dd>Vaini</dd>\n<dt>Country</dt><dd>TO</dd>\n<dt>Current Weather</dt><dd>broken clouds and 78.96 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Requinte Hotel</dd>\n<dt>City</dt><dd>Altamira</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>broken clouds and 78.75 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Sheraton Kauai Coconut Beach Resort</dd>\n<dt>City</dt><dd>Kapaa</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>broken clouds and 80.92 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>HOTEL "SAN JOSE"</dd>\n<dt>City</dt><dd>San Matias</dd>\n<dt>Country</dt><dd>BO</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 80.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Shingu UI Hotel</dd>\n<dt>City</dt><dd>Shingu</dd>\n<dt>Country</dt><dd>JP</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 76.44 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hilo Hawaiian Hotel</dd>\n<dt>City</dt><dd>Hilo</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>clear sky and 83.93 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Dibbo areaمنطقة دبو</dd>\n<dt>City</dt><dd>Kutum</dd>\n<dt>Country</dt><dd>SD</dd>\n<dt>Current Weather</dt><dd>broken clouds and 76.91 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Takalvan Motel</dd>\n<dt>City</dt><dd>Bundaberg</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Current Weather</dt><dd>broken clouds and 75.22 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>People ThankYou</dd>\n<dt>City</dt><dd>Rikitea</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Current Weather</dt><dd>broken clouds and 75.04 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Sea Star Beau Rivage Hotel</dd>\n<dt>City</dt><dd>Hurghada</dd>\n<dt>Country</dt><dd>EG</dd>\n<dt>Current Weather</dt><dd>clear sky and 83.57 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Cititel Penang</dd>\n<dt>City</dt><dd>Georgetown</dd>\n<dt>Country</dt><dd>MY</dd>\n<dt>Current Weather</dt><dd>few clouds and 82.33 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Paradise Inn</dd>\n<dt>City</dt><dd>Avarua</dd>\n<dt>Country</dt><dd>CK</dd>\n<dt>Current Weather</dt><dd>broken clouds and 77.05 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Rio Xingu Camping</dd>\n<dt>City</dt><dd>Sao Felix Do Xingu</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>few clouds and 76.01 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Vanira Lodge</dd>\n<dt>City</dt><dd>Teahupoo</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 76.96 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Holiday Inn Express & Suites Elk Grove Central - Hwy 99, an IHG Hotel</dd>\n<dt>City</dt><dd>Laguna</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>clear sky and 79.32 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hôtel Le Dronmi</dd>\n<dt>City</dt><dd>Cayenne</dd>\n<dt>Country</dt><dd>GF</dd>\n<dt>Current Weather</dt><dd>clear sky and 77.04 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Jallo Kurundingoto Eco Tourist Camp</dd>\n<dt>City</dt><dd>Gunjur</dd>\n<dt>Country</dt><dd>GM</dd>\n<dt>Current Weather</dt><dd>moderate rain and 77.07 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Scoop Guest House</dd>\n<dt>City</dt><dd>Hithadhoo</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 81.52 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Akshaya</dd>\n<dt>City</dt><dd>Annamalainagar</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 79.84 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Castle Motor Lodge Motel</dd>\n<dt>City</dt><dd>Bowen</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 77.74 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Mee seva atk</dd>\n<dt>City</dt><dd>Atmakur</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 75.83 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Motel 6 Sinton, TX</dd>\n<dt>City</dt><dd>San Patricio</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 78.84 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Citra</dd>\n<dt>City</dt><dd>Sabang</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Current Weather</dt><dd>few clouds and 81.99 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hôtel Raiatea Lodge</dd>\n<dt>City</dt><dd>Tevaitoa</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Current Weather</dt><dd>few clouds and 78.98 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel karsa</dd>\n<dt>City</dt><dd>Gabu</dd>\n<dt>Country</dt><dd>GW</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 75.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Bora-Bora Pearl Beach Resort & Spa</dd>\n<dt>City</dt><dd>Faanui</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Current Weather</dt><dd>clear sky and 79.0 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Xaguate</dd>\n<dt>City</dt><dd>Sao Filipe</dd>\n<dt>Country</dt><dd>CV</dd>\n<dt>Current Weather</dt><dd>broken clouds and 77.61 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Principal Paredon</dd>\n<dt>City</dt><dd>Paredon</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Current Weather</dt><dd>few clouds and 79.7 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Suinã</dd>\n<dt>City</dt><dd>Niquelandia</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 75.6 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Grage Hotel Bengkulu</dd>\n<dt>City</dt><dd>Bengkulu</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Current Weather</dt><dd>broken clouds and 79.39 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Motel 6 Santa Ana, CA</dd>\n<dt>City</dt><dd>Santa Ana</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>clear sky and 77.63 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Cassius Hotel</dd>\n<dt>City</dt><dd>Uruacu</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 77.81 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Beso del Viento</dd>\n<dt>City</dt><dd>Parrita</dd>\n<dt>Country</dt><dd>CR</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 78.84 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Whispering Bamboo Cove Resort</dd>\n<dt>City</dt><dd>Morant Bay</dd>\n<dt>Country</dt><dd>JM</dd>\n<dt>Current Weather</dt><dd>broken clouds and 79.84 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>InterContinental Hua Hin Resort, an IHG Hotel</dd>\n<dt>City</dt><dd>Hua Hin</dd>\n<dt>Country</dt><dd>TH</dd>\n<dt>Current Weather</dt><dd>moderate rain and 80.89 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Benjamín Hill</dd>\n<dt>City</dt><dd>Benjamin Hill</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Current Weather</dt><dd>clear sky and 77.4 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>RH HOTEL (4 Star)</dd>\n<dt>City</dt><dd>Sibu</dd>\n<dt>Country</dt><dd>MY</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 75.04 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Floresta Amazonica Hotel</dd>\n<dt>City</dt><dd>Alta Floresta</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 79.86 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Thinadhoo</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 82.27 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>UDIPI HOTEL COMFORTINN</dd>\n<dt>City</dt><dd>Narasapur</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 78.69 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>hotêl doufoulougou</dd>\n<dt>City</dt><dd>Tabou</dd>\n<dt>Country</dt><dd>CI</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 75.24 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Maitai Lapita Village Huahine</dd>\n<dt>City</dt><dd>Fare</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Current Weather</dt><dd>clear sky and 78.96 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Surya Palace</dd>\n<dt>City</dt><dd>Chatakonda</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 76.53 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Lamana Hotel (Port Moresby)</dd>\n<dt>City</dt><dd>Port Moresby</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 84.87 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>St. Agatha Resort</dd>\n<dt>City</dt><dd>Plaridel</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Current Weather</dt><dd>moderate rain and 79.09 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>ibis Styles Karratha</dd>\n<dt>City</dt><dd>Karratha</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Current Weather</dt><dd>clear sky and 81.91 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Rainha do Vale</dd>\n<dt>City</dt><dd>Buritis</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 76.5 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Isles Sunset Lodge</dd>\n<dt>City</dt><dd>Butaritari</dd>\n<dt>Country</dt><dd>KI</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 82.76 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>La Quinta Inn & Suites by Wyndham Buena Park</dd>\n<dt>City</dt><dd>La Palma</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>clear sky and 76.95 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>SanBiz Lodge</dd>\n<dt>City</dt><dd>Kirakira</dd>\n<dt>Country</dt><dd>SB</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 84.45 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Pathein Hotel</dd>\n<dt>City</dt><dd>Pathein</dd>\n<dt>Country</dt><dd>MM</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 81.18 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Best Western Plus Abbey Inn</dd>\n<dt>City</dt><dd>Saint George</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>clear sky and 80.44 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Timotel Hotel</dd>\n<dt>City</dt><dd>Mersing</dd>\n<dt>Country</dt><dd>MY</dd>\n<dt>Current Weather</dt><dd>broken clouds and 83.3 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel</dd>\n<dt>City</dt><dd>Salalah</dd>\n<dt>Country</dt><dd>OM</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 76.96 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Courtyard by Marriott Harlingen</dd>\n<dt>City</dt><dd>Harlingen</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>clear sky and 77.09 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>ธาราริน วิลล่า</dd>\n<dt>City</dt><dd>Doembang Nangbuat</dd>\n<dt>Country</dt><dd>TH</dd>\n<dt>Current Weather</dt><dd>moderate rain and 75.78 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Bungalow 63</dd>\n<dt>City</dt><dd>Hambantota</dd>\n<dt>Country</dt><dd>LK</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 80.91 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Pension Oaoa</dd>\n<dt>City</dt><dd>Tautira</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 78.19 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Jinji</dd>\n<dt>Country</dt><dd>CN</dd>\n<dt>Current Weather</dt><dd>clear sky and 84.54 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Bonthe Holiday Village</dd>\n<dt>City</dt><dd>Bonthe</dd>\n<dt>Country</dt><dd>SL</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 75.47 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Royal Decameron Complex - Puerto Vallarta</dd>\n<dt>City</dt><dd>Bucerias</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 81.99 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Style Inn Shoes Rajanpur</dd>\n<dt>City</dt><dd>Rajanpur</dd>\n<dt>Country</dt><dd>PK</dd>\n<dt>Current Weather</dt><dd>clear sky and 80.94 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>janelas do mar</dd>\n<dt>City</dt><dd>Trairi</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>clear sky and 77.31 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>LT Aparthotel</dd>\n<dt>City</dt><dd>Praia</dd>\n<dt>Country</dt><dd>CV</dd>\n<dt>Current Weather</dt><dd>broken clouds and 79.34 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Leumerus Bungalows</dd>\n<dt>City</dt><dd>Sola</dd>\n<dt>Country</dt><dd>VU</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 80.69 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Shagon mai liverpool</dd>\n<dt>City</dt><dd>Dakoro</dd>\n<dt>Country</dt><dd>NE</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 83.91 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Katsuura Hotel Mikazuki</dd>\n<dt>City</dt><dd>Katsuura</dd>\n<dt>Country</dt><dd>JP</dd>\n<dt>Current Weather</dt><dd>broken clouds and 77.67 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Atlantis Hotel</dd>\n<dt>City</dt><dd>Bathsheba</dd>\n<dt>Country</dt><dd>BB</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 79.41 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Royal Crown Hotel</dd>\n<dt>City</dt><dd>Alexandria</dd>\n<dt>Country</dt><dd>EG</dd>\n<dt>Current Weather</dt><dd>clear sky and 77.97 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Kost Pria</dd>\n<dt>City</dt><dd>Meulaboh</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 79.48 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Sri Venkata Chowdeswari Nilayam</dd>\n<dt>City</dt><dd>Yerraguntla</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Current Weather</dt><dd>broken clouds and 79.02 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Sarah</dd>\n<dt>City</dt><dd>Terra Santa</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 75.56 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>JABIR HOTEL</dd>\n<dt>City</dt><dd>Bandarbeyla</dd>\n<dt>Country</dt><dd>SO</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 77.02 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Shishime Hotel</dd>\n<dt>City</dt><dd>Naze</dd>\n<dt>Country</dt><dd>JP</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 78.89 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Butterfly Beach Hotel</dd>\n<dt>City</dt><dd>Oistins</dd>\n<dt>Country</dt><dd>BB</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 78.89 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Embassy Suites by Hilton Portland Downtown</dd>\n<dt>City</dt><dd>Portland</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Current Weather</dt><dd>clear sky and 81.63 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Country Inn Bed and Breakfast</dd>\n<dt>City</dt><dd>Balangiga</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 84.67 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Pousada Da Praia</dd>\n<dt>City</dt><dd>Nhamunda</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 75.63 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Nuli Sapi</dd>\n<dt>City</dt><dd>Samarai</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Current Weather</dt><dd>broken clouds and 82.42 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Barra Patuca</dd>\n<dt>Country</dt><dd>HN</dd>\n<dt>Current Weather</dt><dd>broken clouds and 78.78 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Big Fish Guest House</dd>\n<dt>City</dt><dd>Corn Island</dd>\n<dt>Country</dt><dd>NI</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 81.86 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Vishnu Residency</dd>\n<dt>City</dt><dd>Khammam</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 76.5 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Ros Muskanan</dd>\n<dt>City</dt><dd>Atambua</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 84.22 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>استراحة الشارب العائلي</dd>\n<dt>City</dt><dd>Awbari</dd>\n<dt>Country</dt><dd>LY</dd>\n<dt>Current Weather</dt><dd>clear sky and 76.82 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>hotel la terminal</dd>\n<dt>City</dt><dd>Ixtapa</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 81.23 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>OYO 598 Peony Hotel</dd>\n<dt>City</dt><dd>Cam Ranh</dd>\n<dt>Country</dt><dd>VN</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 84.16 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>LE SAMANA</dd>\n<dt>City</dt><dd>Mana</dd>\n<dt>Country</dt><dd>GF</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 78.12 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Moon light Furnished Units</dd>\n<dt>City</dt><dd>Umm Lajj</dd>\n<dt>Country</dt><dd>SA</dd>\n<dt>Current Weather</dt><dd>clear sky and 84.09 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Victoria</dd>\n<dt>City</dt><dd>Buenaventura</dd>\n<dt>Country</dt><dd>CO</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 76.03 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Radisson Grenada Beach Resort</dd>\n<dt>City</dt><dd>Saint-Georges</dd>\n<dt>Country</dt><dd>GD</dd>\n<dt>Current Weather</dt><dd>few clouds and 82.08 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Playa Bonita</dd>\n<dt>City</dt><dd>Limon</dd>\n<dt>Country</dt><dd>CR</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 75.06 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd></dd>\n<dt>City</dt><dd>Nioro</dd>\n<dt>Country</dt><dd>GM</dd>\n<dt>Current Weather</dt><dd>moderate rain and 76.06 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Olako</dd>\n<dt>City</dt><dd>Omboue</dd>\n<dt>Country</dt><dd>GA</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 75.09 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Abaco Beach Resort</dd>\n<dt>City</dt><dd>Marsh Harbour</dd>\n<dt>Country</dt><dd>BS</dd>\n<dt>Current Weather</dt><dd>few clouds and 80.6 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>HOTEL DWARKA PALACE</dd>\n<dt>City</dt><dd>Deoli</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Current Weather</dt><dd>clear sky and 76.35 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Shimoda Tokyu Hotel</dd>\n<dt>City</dt><dd>Shimoda</dd>\n<dt>Country</dt><dd>JP</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 75.56 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Lakatoro Palm Lodge</dd>\n<dt>City</dt><dd>Lakatoro</dd>\n<dt>Country</dt><dd>VU</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 83.07 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>KOPKAR Hotel Bintang Sintuk</dd>\n<dt>City</dt><dd>Bontang</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 77.38 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Beau Site</dd>\n<dt>City</dt><dd>Marsa Matruh</dd>\n<dt>Country</dt><dd>EG</dd>\n<dt>Current Weather</dt><dd>clear sky and 76.77 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Pan Tha Tin Guest House - Burmese Only</dd>\n<dt>City</dt><dd>Minbu</dd>\n<dt>Country</dt><dd>MM</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 77.61 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Flat Quatro Rodas Olinda</dd>\n<dt>City</dt><dd>Olinda</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>few clouds and 78.53 °F</dd>\n</dl>\n',

## Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

In [18]:
# Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

# Display sample data
locations.head(10)

        Lat       Lng
0   18.7333 -103.6833
6   -9.8000 -139.0333
7   11.9801   18.2138
13 -21.2000 -175.2000
17  -3.2033  -52.2064
18  22.0752 -159.3190
21 -16.3667  -58.4000
22  33.7333  135.9833
27  19.7297 -155.0900
28  14.2000   24.6667

## Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

In [20]:
# Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Create a figure to add the Google map as a layer
fig = gmaps.figure()
fig.add_layer(marker_layer)


# Display the figure containing the map
fig

Figure(layout=FigureLayout(height='420px'))